// Starter estimates per stated serving; recipes, brands and cooks vary
// widely. This is a reference list to make logging fast, not a verified
// food composition database, and the app says so where it is used.
//
// Generated data: for everything except the twelve original entries the
// kcal figure is 4*protein + 4*carbs + 9*fat, so the energy ring and the
// macro bars can never disagree with each other.
import type { Food } from "./model.ts";

export const catalogue: Food[] = [
  {
    id: "basil",
    name: "ข้าวกะเพราไก่",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 480,
    protein: 25,
    carbs: 62,
    fat: 15,
  },
  {
    id: "papaya",
    name: "ส้มตำไทย",
    emoji: "🥗",
    category: "อาหารตามสั่ง",
    grams: 150,
    unit: "จาน",
    kcal: 120,
    protein: 3,
    carbs: 23,
    fat: 2,
  },
  {
    id: "chicken",
    name: "อกไก่ย่าง",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
  },
  {
    id: "rice",
    name: "ข้าวสวย",
    emoji: "🍚",
    category: "อื่นๆ",
    grams: 80,
    unit: "ทัพพี",
    kcal: 104,
    protein: 2.2,
    carbs: 22.6,
    fat: 0.2,
  },
  {
    id: "egg",
    name: "ไข่ต้ม",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 50,
    unit: "ฟอง",
    kcal: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
  },
  {
    id: "banana",
    name: "กล้วยหอม",
    emoji: "🍌",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ลูก",
    kcal: 107,
    protein: 1.3,
    carbs: 27.4,
    fat: 0.4,
  },
  {
    id: "noodle",
    name: "ก๋วยเตี๋ยวน้ำใส",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 320,
    protein: 18,
    carbs: 45,
    fat: 8,
  },
  {
    id: "salmon",
    name: "แซลมอนย่าง",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
  },
  {
    id: "yogurt",
    name: "โยเกิร์ตรสธรรมชาติ",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 135,
    unit: "ถ้วย",
    kcal: 90,
    protein: 5,
    carbs: 12,
    fat: 2.5,
  },
  {
    id: "apple",
    name: "แอปเปิล",
    emoji: "🍎",
    category: "ผัก ผลไม้",
    grams: 180,
    unit: "ลูก",
    kcal: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
  },
  {
    id: "oats",
    name: "ข้าวโอ๊ต",
    emoji: "🥣",
    category: "อื่นๆ",
    grams: 40,
    unit: "ถ้วยเล็ก",
    kcal: 156,
    protein: 6.8,
    carbs: 26.5,
    fat: 2.8,
  },
  {
    id: "tofu",
    name: "เต้าหู้ขาว",
    emoji: "🧊",
    category: "อื่นๆ",
    grams: 100,
    unit: "ชิ้น",
    kcal: 76,
    protein: 8,
    carbs: 1.9,
    fat: 4.8,
  },
  {
    id: "basil-pork",
    name: "ข้าวกะเพราหมูสับ",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 480,
    protein: 24,
    carbs: 60,
    fat: 16,
  },
  {
    id: "basil-crispy",
    name: "ข้าวกะเพราหมูกรอบ",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 320,
    unit: "จาน",
    kcal: 592,
    protein: 23,
    carbs: 62,
    fat: 28,
  },
  {
    id: "basil-beef",
    name: "ข้าวกะเพราเนื้อ",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 497,
    protein: 26,
    carbs: 60,
    fat: 17,
  },
  {
    id: "basil-seafood",
    name: "ข้าวกะเพราทะเล",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 320,
    unit: "จาน",
    kcal: 456,
    protein: 27,
    carbs: 60,
    fat: 12,
  },
  {
    id: "basil-egg",
    name: "ข้าวกะเพราไก่ไข่ดาว",
    emoji: "🍳",
    category: "อาหารตามสั่ง",
    grams: 360,
    unit: "จาน",
    kcal: 579,
    protein: 31,
    carbs: 62,
    fat: 23,
  },
  {
    id: "friedrice-chicken",
    name: "ข้าวผัดไก่",
    emoji: "🍚",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 438,
    protein: 20,
    carbs: 58,
    fat: 14,
  },
  {
    id: "friedrice-pork",
    name: "ข้าวผัดหมู",
    emoji: "🍚",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 452,
    protein: 19,
    carbs: 58,
    fat: 16,
  },
  {
    id: "friedrice-shrimp",
    name: "ข้าวผัดกุ้ง",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 425,
    protein: 20,
    carbs: 57,
    fat: 13,
  },
  {
    id: "friedrice-crab",
    name: "ข้าวผัดปู",
    emoji: "🦀",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 429,
    protein: 21,
    carbs: 57,
    fat: 13,
  },
  {
    id: "friedrice-american",
    name: "ข้าวผัดอเมริกัน",
    emoji: "🍽️",
    category: "อาหารตามสั่ง",
    grams: 400,
    unit: "จาน",
    kcal: 664,
    protein: 24,
    carbs: 70,
    fat: 32,
  },
  {
    id: "friedrice-shrimppaste",
    name: "ข้าวคลุกกะปิ",
    emoji: "🍚",
    category: "อาหารตามสั่ง",
    grams: 320,
    unit: "จาน",
    kcal: 464,
    protein: 18,
    carbs: 62,
    fat: 16,
  },
  {
    id: "khaomankai",
    name: "ข้าวมันไก่",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 522,
    protein: 28,
    carbs: 62,
    fat: 18,
  },
  {
    id: "khaomankai-fried",
    name: "ข้าวมันไก่ทอด",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 608,
    protein: 27,
    carbs: 62,
    fat: 28,
  },
  {
    id: "khaomudaeng",
    name: "ข้าวหมูแดง",
    emoji: "🍖",
    category: "อาหารตามสั่ง",
    grams: 330,
    unit: "จาน",
    kcal: 478,
    protein: 24,
    carbs: 64,
    fat: 14,
  },
  {
    id: "khaomukrob",
    name: "ข้าวหมูกรอบ",
    emoji: "🥓",
    category: "อาหารตามสั่ง",
    grams: 330,
    unit: "จาน",
    kcal: 606,
    protein: 22,
    carbs: 62,
    fat: 30,
  },
  {
    id: "khakamu",
    name: "ข้าวขาหมู",
    emoji: "🍖",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 586,
    protein: 26,
    carbs: 62,
    fat: 26,
  },
  {
    id: "khaonaped",
    name: "ข้าวหน้าเป็ด",
    emoji: "🦆",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 518,
    protein: 27,
    carbs: 62,
    fat: 18,
  },
  {
    id: "padsee-ew",
    name: "ผัดซีอิ๊วหมู",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 490,
    protein: 20,
    carbs: 62,
    fat: 18,
  },
  {
    id: "padthai",
    name: "ผัดไทยกุ้งสด",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 456,
    protein: 20,
    carbs: 58,
    fat: 16,
  },
  {
    id: "padthai-egg",
    name: "ผัดไทยไข่",
    emoji: "🍳",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 448,
    protein: 16,
    carbs: 60,
    fat: 16,
  },
  {
    id: "radna-pork",
    name: "ราดหน้าหมู",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 380,
    unit: "จาน",
    kcal: 434,
    protein: 19,
    carbs: 58,
    fat: 14,
  },
  {
    id: "radna-seafood",
    name: "ราดหน้าทะเล",
    emoji: "🦑",
    category: "อาหารตามสั่ง",
    grams: 380,
    unit: "จาน",
    kcal: 433,
    protein: 22,
    carbs: 57,
    fat: 13,
  },
  {
    id: "padkeemao",
    name: "ผัดขี้เมาหมู",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 330,
    unit: "จาน",
    kcal: 469,
    protein: 21,
    carbs: 58,
    fat: 17,
  },
  {
    id: "padprikgaeng",
    name: "ผัดพริกแกงหมู",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 458,
    protein: 20,
    carbs: 54,
    fat: 18,
  },
  {
    id: "padkrathiam",
    name: "หมูผัดกระเทียมพริกไทย",
    emoji: "🧄",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 452,
    protein: 23,
    carbs: 54,
    fat: 16,
  },
  {
    id: "greencurry",
    name: "แกงเขียวหวานไก่",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 296,
    protein: 17,
    carbs: 12,
    fat: 20,
  },
  {
    id: "redcurry-duck",
    name: "แกงเผ็ดเป็ดย่าง",
    emoji: "🦆",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 326,
    protein: 19,
    carbs: 13,
    fat: 22,
  },
  {
    id: "massaman",
    name: "แกงมัสมั่นไก่",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 360,
    protein: 18,
    carbs: 18,
    fat: 24,
  },
  {
    id: "panang",
    name: "พะแนงหมู",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "ถ้วย",
    kcal: 314,
    protein: 19,
    carbs: 10,
    fat: 22,
  },
  {
    id: "gaengsom",
    name: "แกงส้มผักรวมกุ้ง",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 131,
    protein: 14,
    carbs: 12,
    fat: 3,
  },
  {
    id: "gaengjued",
    name: "แกงจืดเต้าหู้หมูสับ",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 138,
    protein: 13,
    carbs: 8,
    fat: 6,
  },
  {
    id: "gaengliang",
    name: "แกงเลียง",
    emoji: "🥬",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 94,
    protein: 8,
    carbs: 11,
    fat: 2,
  },
  {
    id: "gaengpa",
    name: "แกงป่าหมู",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 162,
    protein: 18,
    carbs: 9,
    fat: 6,
  },
  {
    id: "curry-yellow",
    name: "แกงกะหรี่ไก่",
    emoji: "🍛",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 298,
    protein: 17,
    carbs: 17,
    fat: 18,
  },
  {
    id: "choochee",
    name: "ฉู่ฉี่ปลาทับทิม",
    emoji: "🐟",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "จาน",
    kcal: 282,
    protein: 21,
    carbs: 9,
    fat: 18,
  },
  {
    id: "tomyumkung",
    name: "ต้มยำกุ้งน้ำใส",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 153,
    protein: 18,
    carbs: 9,
    fat: 5,
  },
  {
    id: "tomyumkung-nam",
    name: "ต้มยำกุ้งน้ำข้น",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 264,
    protein: 18,
    carbs: 12,
    fat: 16,
  },
  {
    id: "tomkhagai",
    name: "ต้มข่าไก่",
    emoji: "🥥",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 284,
    protein: 16,
    carbs: 10,
    fat: 20,
  },
  {
    id: "tomjuedmara",
    name: "ต้มจืดมะระยัดไส้",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 147,
    protein: 13,
    carbs: 8,
    fat: 7,
  },
  {
    id: "tomsaep",
    name: "ต้มแซ่บกระดูกอ่อน",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ถ้วย",
    kcal: 202,
    protein: 20,
    carbs: 8,
    fat: 10,
  },
  {
    id: "noodle-tomyum",
    name: "ก๋วยเตี๋ยวต้มยำ",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 376,
    protein: 19,
    carbs: 48,
    fat: 12,
  },
  {
    id: "noodle-boat",
    name: "ก๋วยเตี๋ยวเรือ",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ชาม",
    kcal: 305,
    protein: 18,
    carbs: 38,
    fat: 9,
  },
  {
    id: "noodle-beef",
    name: "ก๋วยเตี๋ยวเนื้อตุ๋น",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 400,
    unit: "ชาม",
    kcal: 388,
    protein: 24,
    carbs: 46,
    fat: 12,
  },
  {
    id: "noodle-yentafo",
    name: "เย็นตาโฟ",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 400,
    unit: "ชาม",
    kcal: 365,
    protein: 19,
    carbs: 52,
    fat: 9,
  },
  {
    id: "bamee-mudaeng",
    name: "บะหมี่หมูแดง",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "ชาม",
    kcal: 375,
    protein: 21,
    carbs: 48,
    fat: 11,
  },
  {
    id: "bamee-kiew",
    name: "บะหมี่เกี๊ยวกุ้ง",
    emoji: "🥟",
    category: "อาหารตามสั่ง",
    grams: 320,
    unit: "ชาม",
    kcal: 370,
    protein: 20,
    carbs: 50,
    fat: 10,
  },
  {
    id: "kuayjab",
    name: "ก๋วยจั๊บน้ำข้น",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 376,
    protein: 16,
    carbs: 42,
    fat: 16,
  },
  {
    id: "kuayjab-yuan",
    name: "ก๋วยจั๊บญวน",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 334,
    protein: 17,
    carbs: 44,
    fat: 10,
  },
  {
    id: "khanomjeen-namya",
    name: "ขนมจีนน้ำยา",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 378,
    protein: 15,
    carbs: 48,
    fat: 14,
  },
  {
    id: "khanomjeen-ngiew",
    name: "ขนมจีนน้ำเงี้ยว",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 356,
    protein: 16,
    carbs: 46,
    fat: 12,
  },
  {
    id: "padmee-korat",
    name: "ผัดหมี่โคราช",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 406,
    protein: 14,
    carbs: 56,
    fat: 14,
  },
  {
    id: "sukiyaki-dry",
    name: "สุกี้แห้งหมู",
    emoji: "🥘",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "จาน",
    kcal: 382,
    protein: 22,
    carbs: 42,
    fat: 14,
  },
  {
    id: "sukiyaki-soup",
    name: "สุกี้น้ำรวมมิตร",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 400,
    unit: "ชาม",
    kcal: 301,
    protein: 23,
    carbs: 32,
    fat: 9,
  },
  {
    id: "macaroni-fried",
    name: "มักกะโรนีผัดขี้เมา",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 402,
    protein: 17,
    carbs: 52,
    fat: 14,
  },
  {
    id: "spaghetti-tomato",
    name: "สปาเกตตีซอสมะเขือเทศ",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 374,
    protein: 13,
    carbs: 58,
    fat: 10,
  },
  {
    id: "spaghetti-carbonara",
    name: "สปาเกตตีคาโบนาร่า",
    emoji: "🍝",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 548,
    protein: 20,
    carbs: 54,
    fat: 28,
  },
  {
    id: "somtam-poo",
    name: "ส้มตำปูปลาร้า",
    emoji: "🦀",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 139,
    protein: 8,
    carbs: 20,
    fat: 3,
  },
  {
    id: "somtam-thai-kai",
    name: "ส้มตำไทยไข่เค็ม",
    emoji: "🥚",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "จาน",
    kcal: 200,
    protein: 10,
    carbs: 22,
    fat: 8,
  },
  {
    id: "yumwoonsen",
    name: "ยำวุ้นเส้น",
    emoji: "🥗",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 222,
    protein: 14,
    carbs: 28,
    fat: 6,
  },
  {
    id: "yum-mama",
    name: "ยำมาม่า",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "จาน",
    kcal: 346,
    protein: 13,
    carbs: 42,
    fat: 14,
  },
  {
    id: "larb-moo",
    name: "ลาบหมู",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 228,
    protein: 22,
    carbs: 8,
    fat: 12,
  },
  {
    id: "namtok-moo",
    name: "น้ำตกหมู",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 237,
    protein: 23,
    carbs: 7,
    fat: 13,
  },
  {
    id: "larb-gai",
    name: "ลาบไก่",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 196,
    protein: 24,
    carbs: 7,
    fat: 8,
  },
  {
    id: "plakung",
    name: "พล่ากุ้ง",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 148,
    protein: 20,
    carbs: 8,
    fat: 4,
  },
  {
    id: "yum-moo-yor",
    name: "ยำหมูยอ",
    emoji: "🥗",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 200,
    protein: 13,
    carbs: 10,
    fat: 12,
  },
  {
    id: "yum-talay",
    name: "ยำทะเล",
    emoji: "🦑",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 172,
    protein: 24,
    carbs: 10,
    fat: 4,
  },
  {
    id: "kai-tod",
    name: "ไก่ทอด",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 120,
    unit: "ชิ้น",
    kcal: 290,
    protein: 22,
    carbs: 10,
    fat: 18,
  },
  {
    id: "kai-yang",
    name: "ไก่ย่าง",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 120,
    unit: "ชิ้น",
    kcal: 206,
    protein: 26,
    carbs: 3,
    fat: 10,
  },
  {
    id: "peek-kai-tod",
    name: "ปีกไก่ทอด",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 60,
    unit: "ชิ้น",
    kcal: 163,
    protein: 11,
    carbs: 5,
    fat: 11,
  },
  {
    id: "moo-ping",
    name: "หมูปิ้ง",
    emoji: "🍢",
    category: "อาหารตามสั่ง",
    grams: 40,
    unit: "ไม้",
    kcal: 89,
    protein: 7,
    carbs: 4,
    fat: 5,
  },
  {
    id: "luk-chin-ping",
    name: "ลูกชิ้นปิ้ง",
    emoji: "🍢",
    category: "อาหารตามสั่ง",
    grams: 50,
    unit: "ไม้",
    kcal: 96,
    protein: 6,
    carbs: 9,
    fat: 4,
  },
  {
    id: "moo-tod",
    name: "หมูทอดกระเทียม",
    emoji: "🥓",
    category: "อาหารตามสั่ง",
    grams: 150,
    unit: "จาน",
    kcal: 308,
    protein: 26,
    carbs: 6,
    fat: 20,
  },
  {
    id: "pla-tod",
    name: "ปลาทอดน้ำปลา",
    emoji: "🐟",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "ตัว",
    kcal: 272,
    protein: 30,
    carbs: 2,
    fat: 16,
  },
  {
    id: "pla-nueng-manao",
    name: "ปลานึ่งมะนาว",
    emoji: "🐟",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ตัว",
    kcal: 231,
    protein: 36,
    carbs: 6,
    fat: 7,
  },
  {
    id: "pla-pao",
    name: "ปลาเผา",
    emoji: "🐟",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ตัว",
    kcal: 245,
    protein: 38,
    carbs: 3,
    fat: 9,
  },
  {
    id: "goong-tod",
    name: "กุ้งทอดกระเทียม",
    emoji: "🍤",
    category: "อาหารตามสั่ง",
    grams: 150,
    unit: "จาน",
    kcal: 254,
    protein: 26,
    carbs: 6,
    fat: 14,
  },
  {
    id: "pumeng-padpongkaree",
    name: "ปูผัดผงกะหรี่",
    emoji: "🦀",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 358,
    protein: 26,
    carbs: 14,
    fat: 22,
  },
  {
    id: "hoy-lai-padprik",
    name: "หอยลายผัดพริกเผา",
    emoji: "🐚",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 218,
    protein: 22,
    carbs: 10,
    fat: 10,
  },
  {
    id: "pladuk-foo",
    name: "ปลาดุกฟู",
    emoji: "🐟",
    category: "อาหารตามสั่ง",
    grams: 120,
    unit: "จาน",
    kcal: 302,
    protein: 18,
    carbs: 8,
    fat: 22,
  },
  {
    id: "kai-jiew",
    name: "ไข่เจียวหมูสับ",
    emoji: "🍳",
    category: "อาหารตามสั่ง",
    grams: 120,
    unit: "จาน",
    kcal: 252,
    protein: 15,
    carbs: 3,
    fat: 20,
  },
  {
    id: "khao-kai-jiew",
    name: "ข้าวไข่เจียว",
    emoji: "🍳",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 441,
    protein: 17,
    carbs: 46,
    fat: 21,
  },
  {
    id: "kai-dao",
    name: "ไข่ดาว",
    emoji: "🍳",
    category: "อาหารตามสั่ง",
    grams: 55,
    unit: "ฟอง",
    kcal: 109,
    protein: 6.5,
    carbs: 0.5,
    fat: 9,
  },
  {
    id: "khao-tom-moo",
    name: "ข้าวต้มหมู",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 262,
    protein: 14,
    carbs: 38,
    fat: 6,
  },
  {
    id: "jok-moo",
    name: "โจ๊กหมูไข่",
    emoji: "🍲",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 280,
    protein: 16,
    carbs: 36,
    fat: 8,
  },
  {
    id: "khao-niew-moo-ping",
    name: "ข้าวเหนียวหมูปิ้ง",
    emoji: "🍢",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "ชุด",
    kcal: 346,
    protein: 16,
    carbs: 48,
    fat: 10,
  },
  {
    id: "sandwich-ham",
    name: "แซนด์วิชแฮมชีส",
    emoji: "🥪",
    category: "อาหารตามสั่ง",
    grams: 150,
    unit: "ชิ้น",
    kcal: 318,
    protein: 16,
    carbs: 32,
    fat: 14,
  },
  {
    id: "burger-beef",
    name: "เบอร์เกอร์เนื้อ",
    emoji: "🍔",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "ชิ้น",
    kcal: 468,
    protein: 25,
    carbs: 38,
    fat: 24,
  },
  {
    id: "pizza-slice",
    name: "พิซซ่า",
    emoji: "🍕",
    category: "อาหารตามสั่ง",
    grams: 120,
    unit: "ชิ้น",
    kcal: 275,
    protein: 12,
    carbs: 32,
    fat: 11,
  },
  {
    id: "sushi-set",
    name: "ซูชิรวม",
    emoji: "🍣",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "ชุด",
    kcal: 317,
    protein: 16,
    carbs: 52,
    fat: 5,
  },
  {
    id: "gyudon",
    name: "ข้าวหน้าเนื้อ",
    emoji: "🍚",
    category: "อาหารตามสั่ง",
    grams: 350,
    unit: "ชาม",
    kcal: 504,
    protein: 24,
    carbs: 66,
    fat: 16,
  },
  {
    id: "katsudon",
    name: "ข้าวหน้าหมูทอดไข่",
    emoji: "🍚",
    category: "อาหารตามสั่ง",
    grams: 380,
    unit: "ชาม",
    kcal: 618,
    protein: 26,
    carbs: 70,
    fat: 26,
  },
  {
    id: "ramen-shoyu",
    name: "ราเมงโชยุ",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 450,
    unit: "ชาม",
    kcal: 480,
    protein: 24,
    carbs: 60,
    fat: 16,
  },
  {
    id: "steak-chicken",
    name: "สเต๊กไก่",
    emoji: "🍗",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 350,
    protein: 38,
    carbs: 18,
    fat: 14,
  },
  {
    id: "steak-pork",
    name: "สเต๊กหมู",
    emoji: "🥩",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 396,
    protein: 36,
    carbs: 18,
    fat: 20,
  },
  {
    id: "salad-caesar",
    name: "สลัดซีซาร์ไก่",
    emoji: "🥗",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 316,
    protein: 22,
    carbs: 12,
    fat: 20,
  },
  {
    id: "salad-veg",
    name: "สลัดผักน้ำใส",
    emoji: "🥗",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 91,
    protein: 4,
    carbs: 12,
    fat: 3,
  },
  {
    id: "khao-pad-kaprao-jay",
    name: "ข้าวผัดกะเพราเจ",
    emoji: "🥬",
    category: "อาหารตามสั่ง",
    grams: 300,
    unit: "จาน",
    kcal: 406,
    protein: 12,
    carbs: 58,
    fat: 14,
  },
  {
    id: "pad-pak-ruam",
    name: "ผัดผักรวมมิตร",
    emoji: "🥦",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "จาน",
    kcal: 170,
    protein: 6,
    carbs: 14,
    fat: 10,
  },
  {
    id: "pak-boong-fai-daeng",
    name: "ผัดผักบุ้งไฟแดง",
    emoji: "🥬",
    category: "อาหารตามสั่ง",
    grams: 180,
    unit: "จาน",
    kcal: 146,
    protein: 4,
    carbs: 10,
    fat: 10,
  },
  {
    id: "kana-moo-krob",
    name: "คะน้าหมูกรอบ",
    emoji: "🥬",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "จาน",
    kcal: 328,
    protein: 16,
    carbs: 12,
    fat: 24,
  },
  {
    id: "tao-hoo-song-kreung",
    name: "เต้าหู้ทรงเครื่อง",
    emoji: "🧊",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "จาน",
    kcal: 242,
    protein: 15,
    carbs: 14,
    fat: 14,
  },
  {
    id: "kai-palo",
    name: "ไข่พะโล้",
    emoji: "🥚",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "ถ้วย",
    kcal: 264,
    protein: 18,
    carbs: 12,
    fat: 16,
  },
  {
    id: "moo-hong",
    name: "หมูฮ้อง",
    emoji: "🍖",
    category: "อาหารตามสั่ง",
    grams: 220,
    unit: "ถ้วย",
    kcal: 326,
    protein: 20,
    carbs: 12,
    fat: 22,
  },
  {
    id: "nam-prik-kapi-set",
    name: "น้ำพริกกะปิผักสด",
    emoji: "🌶️",
    category: "อาหารตามสั่ง",
    grams: 200,
    unit: "ชุด",
    kcal: 150,
    protein: 10,
    carbs: 14,
    fat: 6,
  },
  {
    id: "khai-luk-khoei",
    name: "ไข่ลูกเขย",
    emoji: "🥚",
    category: "อาหารตามสั่ง",
    grams: 150,
    unit: "จาน",
    kcal: 268,
    protein: 13,
    carbs: 18,
    fat: 16,
  },
  {
    id: "hoy-tod",
    name: "หอยทอด",
    emoji: "🦪",
    category: "อาหารตามสั่ง",
    grams: 250,
    unit: "จาน",
    kcal: 456,
    protein: 16,
    carbs: 44,
    fat: 24,
  },
  {
    id: "khanom-pang-na-moo",
    name: "ขนมปังหน้าหมู",
    emoji: "🍞",
    category: "อาหารตามสั่ง",
    grams: 40,
    unit: "ชิ้น",
    kcal: 110,
    protein: 4,
    carbs: 10,
    fat: 6,
  },
  {
    id: "por-pia-tod",
    name: "ปอเปี๊ยะทอด",
    emoji: "🥟",
    category: "อาหารตามสั่ง",
    grams: 40,
    unit: "ชิ้น",
    kcal: 89,
    protein: 3,
    carbs: 8,
    fat: 5,
  },
  {
    id: "kanom-jeeb",
    name: "ขนมจีบ",
    emoji: "🥟",
    category: "อาหารตามสั่ง",
    grams: 25,
    unit: "ชิ้น",
    kcal: 40,
    protein: 2.5,
    carbs: 4,
    fat: 1.5,
  },
  {
    id: "salapao-moo",
    name: "ซาลาเปาไส้หมู",
    emoji: "🥟",
    category: "อาหารตามสั่ง",
    grams: 90,
    unit: "ลูก",
    kcal: 206,
    protein: 8,
    carbs: 30,
    fat: 6,
  },
  {
    id: "tom-yum-instant",
    name: "มาม่าต้มยำ",
    emoji: "🍜",
    category: "อาหารตามสั่ง",
    grams: 60,
    unit: "ซอง",
    kcal: 362,
    protein: 7,
    carbs: 52,
    fat: 14,
  },
  {
    id: "pak-boong",
    name: "ผักบุ้งลวก",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 25,
    protein: 2.6,
    carbs: 3.1,
    fat: 0.2,
  },
  {
    id: "kana",
    name: "คะน้าลวก",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 40,
    protein: 3,
    carbs: 5.5,
    fat: 0.7,
  },
  {
    id: "broccoli",
    name: "บรอกโคลีลวก",
    emoji: "🥦",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 43,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
  },
  {
    id: "cauliflower",
    name: "กะหล่ำดอกลวก",
    emoji: "🥦",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 30,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
  },
  {
    id: "cabbage",
    name: "กะหล่ำปลี",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 29,
    protein: 1.3,
    carbs: 5.8,
    fat: 0.1,
  },
  {
    id: "chinese-cabbage",
    name: "ผักกาดขาว",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 15,
    protein: 1.2,
    carbs: 2.2,
    fat: 0.2,
  },
  {
    id: "lettuce",
    name: "ผักกาดหอม",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 19,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
  },
  {
    id: "spinach",
    name: "ผักโขม",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 30,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
  },
  {
    id: "tumlung",
    name: "ตำลึง",
    emoji: "🥬",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 34,
    protein: 3.3,
    carbs: 4.2,
    fat: 0.4,
  },
  {
    id: "cha-om",
    name: "ชะอม",
    emoji: "🌿",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 60,
    protein: 8.2,
    carbs: 5,
    fat: 0.8,
  },
  {
    id: "dok-khae",
    name: "ดอกแค",
    emoji: "🌸",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 35,
    protein: 1.5,
    carbs: 6.7,
    fat: 0.2,
  },
  {
    id: "cucumber",
    name: "แตงกวา",
    emoji: "🥒",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ลูก",
    kcal: 22,
    protein: 0.8,
    carbs: 4.4,
    fat: 0.1,
  },
  {
    id: "tomato",
    name: "มะเขือเทศ",
    emoji: "🍅",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ลูก",
    kcal: 25,
    protein: 1.1,
    carbs: 4.7,
    fat: 0.2,
  },
  {
    id: "carrot",
    name: "แครอท",
    emoji: "🥕",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "หัว",
    kcal: 44,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
  },
  {
    id: "pumpkin",
    name: "ฟักทองนึ่ง",
    emoji: "🎃",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 53,
    protein: 1,
    carbs: 12,
    fat: 0.1,
  },
  {
    id: "long-bean",
    name: "ถั่วฝักยาว",
    emoji: "🫛",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 47,
    protein: 2.8,
    carbs: 8,
    fat: 0.4,
  },
  {
    id: "bean-sprout",
    name: "ถั่วงอก",
    emoji: "🌱",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 37,
    protein: 3,
    carbs: 5.9,
    fat: 0.2,
  },
  {
    id: "corn-boiled",
    name: "ข้าวโพดต้ม",
    emoji: "🌽",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ฝัก",
    kcal: 148,
    protein: 4.9,
    carbs: 28,
    fat: 1.8,
  },
  {
    id: "baby-corn",
    name: "ข้าวโพดอ่อน",
    emoji: "🌽",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 31,
    protein: 1.9,
    carbs: 5.5,
    fat: 0.2,
  },
  {
    id: "eggplant",
    name: "มะเขือยาว",
    emoji: "🍆",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ลูก",
    kcal: 35,
    protein: 1.2,
    carbs: 7,
    fat: 0.2,
  },
  {
    id: "bitter-gourd",
    name: "มะระ",
    emoji: "🥒",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 23,
    protein: 1,
    carbs: 4.3,
    fat: 0.2,
  },
  {
    id: "luffa",
    name: "บวบ",
    emoji: "🥒",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 24,
    protein: 1.2,
    carbs: 4.4,
    fat: 0.2,
  },
  {
    id: "bamboo-shoot",
    name: "หน่อไม้ต้ม",
    emoji: "🎋",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 34,
    protein: 2.6,
    carbs: 5.2,
    fat: 0.3,
  },
  {
    id: "bell-pepper",
    name: "พริกหวาน",
    emoji: "🫑",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ลูก",
    kcal: 35,
    protein: 1,
    carbs: 7,
    fat: 0.3,
  },
  {
    id: "mushroom-oyster",
    name: "เห็ดนางฟ้า",
    emoji: "🍄",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 41,
    protein: 3.3,
    carbs: 6.1,
    fat: 0.4,
  },
  {
    id: "mushroom-king",
    name: "เห็ดออรินจิ",
    emoji: "🍄",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 38,
    protein: 2.7,
    carbs: 6,
    fat: 0.3,
  },
  {
    id: "mushroom-shiitake",
    name: "เห็ดหอม",
    emoji: "🍄",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 40,
    protein: 2.2,
    carbs: 6.8,
    fat: 0.5,
  },
  {
    id: "okra",
    name: "กระเจี๊ยบเขียว",
    emoji: "🌿",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 39,
    protein: 1.9,
    carbs: 7.5,
    fat: 0.2,
  },
  {
    id: "sator",
    name: "สะตอ",
    emoji: "🫘",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 102,
    protein: 8,
    carbs: 14,
    fat: 1.5,
  },
  {
    id: "winged-bean",
    name: "ถั่วพู",
    emoji: "🫛",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 68,
    protein: 6.9,
    carbs: 8,
    fat: 0.9,
  },
  {
    id: "morning-glory-stem",
    name: "ยอดมะพร้าวอ่อน",
    emoji: "🥥",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 40,
    protein: 1.5,
    carbs: 8,
    fat: 0.2,
  },
  {
    id: "onion",
    name: "หัวหอมใหญ่",
    emoji: "🧅",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "หัว",
    kcal: 42,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
  },
  {
    id: "spring-onion",
    name: "ต้นหอม",
    emoji: "🌿",
    category: "ผัก ผลไม้",
    grams: 50,
    unit: "ถ้วย",
    kcal: 19,
    protein: 0.9,
    carbs: 3.7,
    fat: 0.1,
  },
  {
    id: "coriander",
    name: "ผักชี",
    emoji: "🌿",
    category: "ผัก ผลไม้",
    grams: 30,
    unit: "ถ้วย",
    kcal: 8,
    protein: 0.6,
    carbs: 1.1,
    fat: 0.1,
  },
  {
    id: "basil-leaf",
    name: "ใบโหระพา",
    emoji: "🌿",
    category: "ผัก ผลไม้",
    grams: 30,
    unit: "ถ้วย",
    kcal: 9,
    protein: 1,
    carbs: 0.8,
    fat: 0.2,
  },
  {
    id: "banana-namwa",
    name: "กล้วยน้ำว้า",
    emoji: "🍌",
    category: "ผัก ผลไม้",
    grams: 70,
    unit: "ลูก",
    kcal: 68,
    protein: 0.8,
    carbs: 15.8,
    fat: 0.2,
  },
  {
    id: "orange",
    name: "ส้มเขียวหวาน",
    emoji: "🍊",
    category: "ผัก ผลไม้",
    grams: 130,
    unit: "ลูก",
    kcal: 53,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.2,
  },
  {
    id: "pomelo",
    name: "ส้มโอ",
    emoji: "🍊",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "กลีบ",
    kcal: 64,
    protein: 1.2,
    carbs: 14.6,
    fat: 0.1,
  },
  {
    id: "mango-ripe",
    name: "มะม่วงสุก",
    emoji: "🥭",
    category: "ผัก ผลไม้",
    grams: 200,
    unit: "ลูก",
    kcal: 124,
    protein: 1.6,
    carbs: 28,
    fat: 0.6,
  },
  {
    id: "mango-green",
    name: "มะม่วงดิบ",
    emoji: "🥭",
    category: "ผัก ผลไม้",
    grams: 200,
    unit: "ลูก",
    kcal: 76,
    protein: 1,
    carbs: 17,
    fat: 0.4,
  },
  {
    id: "pineapple",
    name: "สับปะรด",
    emoji: "🍍",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 83,
    protein: 0.8,
    carbs: 19.5,
    fat: 0.2,
  },
  {
    id: "watermelon",
    name: "แตงโม",
    emoji: "🍉",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 51,
    protein: 0.9,
    carbs: 11.5,
    fat: 0.2,
  },
  {
    id: "papaya-fruit",
    name: "มะละกอสุก",
    emoji: "🧡",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 66,
    protein: 0.7,
    carbs: 15,
    fat: 0.4,
  },
  {
    id: "guava",
    name: "ฝรั่ง",
    emoji: "🍏",
    category: "ผัก ผลไม้",
    grams: 180,
    unit: "ลูก",
    kcal: 133,
    protein: 4.6,
    carbs: 25,
    fat: 1.6,
  },
  {
    id: "rose-apple",
    name: "ชมพู่",
    emoji: "🍎",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ลูก",
    kcal: 28,
    protein: 0.6,
    carbs: 5.7,
    fat: 0.3,
  },
  {
    id: "grape",
    name: "องุ่นเขียว",
    emoji: "🍇",
    category: "ผัก ผลไม้",
    grams: 120,
    unit: "ถ้วย",
    kcal: 89,
    protein: 0.7,
    carbs: 21,
    fat: 0.2,
  },
  {
    id: "lychee",
    name: "ลิ้นจี่",
    emoji: "🫐",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 73,
    protein: 0.8,
    carbs: 16.5,
    fat: 0.4,
  },
  {
    id: "longan",
    name: "ลำไย",
    emoji: "🫐",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 66,
    protein: 1.3,
    carbs: 15.1,
    fat: 0.1,
  },
  {
    id: "rambutan",
    name: "เงาะ",
    emoji: "🔴",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 88,
    protein: 0.7,
    carbs: 20.9,
    fat: 0.2,
  },
  {
    id: "durian",
    name: "ทุเรียนหมอนทอง",
    emoji: "🟡",
    category: "ผัก ผลไม้",
    grams: 80,
    unit: "พู",
    kcal: 131,
    protein: 1.2,
    carbs: 22,
    fat: 4.2,
  },
  {
    id: "mangosteen",
    name: "มังคุด",
    emoji: "🟣",
    category: "ผัก ผลไม้",
    grams: 80,
    unit: "ลูก",
    kcal: 59,
    protein: 0.4,
    carbs: 14,
    fat: 0.2,
  },
  {
    id: "jackfruit",
    name: "ขนุน",
    emoji: "🟡",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 158,
    protein: 2.5,
    carbs: 35,
    fat: 0.9,
  },
  {
    id: "cantaloupe",
    name: "แคนตาลูป",
    emoji: "🍈",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 55,
    protein: 0.8,
    carbs: 12.5,
    fat: 0.2,
  },
  {
    id: "strawberry",
    name: "สตรอว์เบอร์รี",
    emoji: "🍓",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 54,
    protein: 1,
    carbs: 11.5,
    fat: 0.5,
  },
  {
    id: "blueberry",
    name: "บลูเบอร์รี",
    emoji: "🫐",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 64,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
  },
  {
    id: "kiwi",
    name: "กีวี",
    emoji: "🥝",
    category: "ผัก ผลไม้",
    grams: 90,
    unit: "ลูก",
    kcal: 58,
    protein: 1,
    carbs: 12.5,
    fat: 0.5,
  },
  {
    id: "dragonfruit",
    name: "แก้วมังกร",
    emoji: "🐉",
    category: "ผัก ผลไม้",
    grams: 200,
    unit: "ลูก",
    kcal: 92,
    protein: 2,
    carbs: 20,
    fat: 0.4,
  },
  {
    id: "sapodilla",
    name: "ละมุด",
    emoji: "🟤",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ลูก",
    kcal: 92,
    protein: 0.4,
    carbs: 20,
    fat: 1.1,
  },
  {
    id: "custard-apple",
    name: "น้อยหน่า",
    emoji: "🟢",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ลูก",
    kcal: 116,
    protein: 2.1,
    carbs: 25,
    fat: 0.9,
  },
  {
    id: "jujube",
    name: "พุทรา",
    emoji: "🟠",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 87,
    protein: 1.2,
    carbs: 20.2,
    fat: 0.2,
  },
  {
    id: "tamarind-sweet",
    name: "มะขามหวาน",
    emoji: "🟤",
    category: "ผัก ผลไม้",
    grams: 20,
    unit: "ฝัก",
    kcal: 53,
    protein: 0.6,
    carbs: 12.5,
    fat: 0.1,
  },
  {
    id: "persimmon",
    name: "ลูกพลับ",
    emoji: "🟠",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ลูก",
    kcal: 106,
    protein: 0.9,
    carbs: 25,
    fat: 0.3,
  },
  {
    id: "avocado",
    name: "อะโวคาโด",
    emoji: "🥑",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ลูก",
    kcal: 258,
    protein: 3,
    carbs: 12,
    fat: 22,
  },
  {
    id: "pomegranate",
    name: "ทับทิม",
    emoji: "🔴",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ถ้วย",
    kcal: 121,
    protein: 2.5,
    carbs: 24,
    fat: 1.7,
  },
  {
    id: "coconut-young",
    name: "มะพร้าวอ่อน",
    emoji: "🥥",
    category: "ผัก ผลไม้",
    grams: 200,
    unit: "ลูก",
    kcal: 45,
    protein: 1.4,
    carbs: 9,
    fat: 0.4,
  },
  {
    id: "passionfruit",
    name: "เสาวรส",
    emoji: "🟣",
    category: "ผัก ผลไม้",
    grams: 50,
    unit: "ลูก",
    kcal: 53,
    protein: 1.1,
    carbs: 11.5,
    fat: 0.3,
  },
  {
    id: "santol",
    name: "กระท้อน",
    emoji: "🟡",
    category: "ผัก ผลไม้",
    grams: 150,
    unit: "ลูก",
    kcal: 62,
    protein: 1,
    carbs: 14,
    fat: 0.2,
  },
  {
    id: "langsat",
    name: "ลองกอง",
    emoji: "🟡",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 62,
    protein: 1,
    carbs: 14,
    fat: 0.2,
  },
  {
    id: "salak",
    name: "สละ",
    emoji: "🟤",
    category: "ผัก ผลไม้",
    grams: 100,
    unit: "ถ้วย",
    kcal: 73,
    protein: 0.8,
    carbs: 17,
    fat: 0.2,
  },
  {
    id: "banana-fried-plain",
    name: "กล้วยตาก",
    emoji: "🍌",
    category: "ผัก ผลไม้",
    grams: 30,
    unit: "ชิ้น",
    kcal: 89,
    protein: 0.9,
    carbs: 21,
    fat: 0.2,
  },
  {
    id: "chicken-thigh",
    name: "น่องไก่ไม่มีหนัง",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 168,
    protein: 24,
    carbs: 0,
    fat: 8,
  },
  {
    id: "chicken-drumstick",
    name: "สะโพกไก่",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 120,
    unit: "ชิ้น",
    kcal: 187,
    protein: 22,
    carbs: 0,
    fat: 11,
  },
  {
    id: "chicken-wing",
    name: "ปีกไก่",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 50,
    unit: "ชิ้น",
    kcal: 99,
    protein: 9,
    carbs: 0,
    fat: 7,
  },
  {
    id: "chicken-skin",
    name: "หนังไก่",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 30,
    unit: "ชิ้น",
    kcal: 124,
    protein: 4,
    carbs: 0,
    fat: 12,
  },
  {
    id: "chicken-ground",
    name: "ไก่บด",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 164,
    protein: 23,
    carbs: 0,
    fat: 8,
  },
  {
    id: "pork-tenderloin",
    name: "หมูสันใน",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 120,
    protein: 22,
    carbs: 0,
    fat: 3.5,
  },
  {
    id: "pork-loin",
    name: "หมูสันนอก",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 147,
    protein: 21,
    carbs: 0,
    fat: 7,
  },
  {
    id: "pork-belly",
    name: "หมูสามชั้น",
    emoji: "🥓",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 375,
    protein: 15,
    carbs: 0,
    fat: 35,
  },
  {
    id: "pork-ground",
    name: "หมูสับ",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 188,
    protein: 20,
    carbs: 0,
    fat: 12,
  },
  {
    id: "pork-neck",
    name: "คอหมูย่าง",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 219,
    protein: 20,
    carbs: 1,
    fat: 15,
  },
  {
    id: "pork-rib",
    name: "ซี่โครงหมู",
    emoji: "🍖",
    category: "เนื้อสัตว์",
    grams: 120,
    unit: "ชิ้น",
    kcal: 242,
    protein: 20,
    carbs: 0,
    fat: 18,
  },
  {
    id: "pork-crispy",
    name: "หมูกรอบ",
    emoji: "🥓",
    category: "เนื้อสัตว์",
    grams: 80,
    unit: "ถ้วย",
    kcal: 360,
    protein: 17,
    carbs: 1,
    fat: 32,
  },
  {
    id: "beef-tenderloin",
    name: "เนื้อสันใน",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 142,
    protein: 22,
    carbs: 0,
    fat: 6,
  },
  {
    id: "beef-rump",
    name: "เนื้อสะโพก",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 165,
    protein: 21,
    carbs: 0,
    fat: 9,
  },
  {
    id: "beef-ground",
    name: "เนื้อบด",
    emoji: "🥩",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 215,
    protein: 20,
    carbs: 0,
    fat: 15,
  },
  {
    id: "duck-roast",
    name: "เป็ดย่าง",
    emoji: "🦆",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ชิ้น",
    kcal: 260,
    protein: 19,
    carbs: 1,
    fat: 20,
  },
  {
    id: "shrimp-white",
    name: "กุ้งขาว",
    emoji: "🍤",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 90,
    protein: 20,
    carbs: 0.2,
    fat: 1,
  },
  {
    id: "shrimp-river",
    name: "กุ้งแม่น้ำ",
    emoji: "🦐",
    category: "เนื้อสัตว์",
    grams: 80,
    unit: "ตัว",
    kcal: 79,
    protein: 15,
    carbs: 0.2,
    fat: 2,
  },
  {
    id: "mackerel",
    name: "ปลาทูนึ่ง",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 80,
    unit: "ตัว",
    kcal: 140,
    protein: 17,
    carbs: 0,
    fat: 8,
  },
  {
    id: "tilapia",
    name: "ปลานิล",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 150,
    unit: "ตัว",
    kcal: 131,
    protein: 26,
    carbs: 0,
    fat: 3,
  },
  {
    id: "red-tilapia",
    name: "ปลาทับทิม",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 150,
    unit: "ตัว",
    kcal: 144,
    protein: 27,
    carbs: 0,
    fat: 4,
  },
  {
    id: "seabass",
    name: "ปลากะพง",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 150,
    unit: "ชิ้น",
    kcal: 148,
    protein: 28,
    carbs: 0,
    fat: 4,
  },
  {
    id: "tuna-can",
    name: "ปลาทูน่าในน้ำแร่",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 80,
    unit: "กระป๋อง",
    kcal: 85,
    protein: 19,
    carbs: 0,
    fat: 1,
  },
  {
    id: "saba",
    name: "ปลาซาบะย่าง",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 120,
    unit: "ชิ้น",
    kcal: 267,
    protein: 24,
    carbs: 0,
    fat: 19,
  },
  {
    id: "pla-salid",
    name: "ปลาสลิดทอด",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 50,
    unit: "ตัว",
    kcal: 133,
    protein: 13,
    carbs: 0,
    fat: 9,
  },
  {
    id: "squid",
    name: "ปลาหมึกกล้วย",
    emoji: "🦑",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 89,
    protein: 16,
    carbs: 3,
    fat: 1.4,
  },
  {
    id: "mussel",
    name: "หอยแมลงภู่",
    emoji: "🦪",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 92,
    protein: 14,
    carbs: 4,
    fat: 2.2,
  },
  {
    id: "clam",
    name: "หอยลาย",
    emoji: "🐚",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 73,
    protein: 13,
    carbs: 3,
    fat: 1,
  },
  {
    id: "oyster",
    name: "หอยนางรม",
    emoji: "🦪",
    category: "เนื้อสัตว์",
    grams: 30,
    unit: "ตัว",
    kcal: 19,
    protein: 2.1,
    carbs: 1.2,
    fat: 0.6,
  },
  {
    id: "crab",
    name: "ปูม้านึ่ง",
    emoji: "🦀",
    category: "เนื้อสัตว์",
    grams: 120,
    unit: "ตัว",
    kcal: 94,
    protein: 20,
    carbs: 0,
    fat: 1.5,
  },
  {
    id: "crab-stick",
    name: "ปูอัด",
    emoji: "🦀",
    category: "เนื้อสัตว์",
    grams: 25,
    unit: "ชิ้น",
    kcal: 21,
    protein: 1.5,
    carbs: 3,
    fat: 0.3,
  },
  {
    id: "fish-ball",
    name: "ลูกชิ้นปลา",
    emoji: "⚪",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 106,
    protein: 10,
    carbs: 12,
    fat: 2,
  },
  {
    id: "pork-ball",
    name: "ลูกชิ้นหมู",
    emoji: "⚪",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 160,
    protein: 12,
    carbs: 10,
    fat: 8,
  },
  {
    id: "beef-ball",
    name: "ลูกชิ้นเนื้อ",
    emoji: "⚪",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 169,
    protein: 13,
    carbs: 9,
    fat: 9,
  },
  {
    id: "sausage",
    name: "ไส้กรอกหมู",
    emoji: "🌭",
    category: "เนื้อสัตว์",
    grams: 50,
    unit: "ชิ้น",
    kcal: 148,
    protein: 7,
    carbs: 3,
    fat: 12,
  },
  {
    id: "ham",
    name: "แฮม",
    emoji: "🥓",
    category: "เนื้อสัตว์",
    grams: 30,
    unit: "แผ่น",
    kcal: 36,
    protein: 5,
    carbs: 0.5,
    fat: 1.5,
  },
  {
    id: "bacon",
    name: "เบคอน",
    emoji: "🥓",
    category: "เนื้อสัตว์",
    grams: 20,
    unit: "แผ่น",
    kcal: 77,
    protein: 3.5,
    carbs: 0.1,
    fat: 7,
  },
  {
    id: "moo-yor",
    name: "หมูยอ",
    emoji: "🍖",
    category: "เนื้อสัตว์",
    grams: 50,
    unit: "ชิ้น",
    kcal: 112,
    protein: 6,
    carbs: 4,
    fat: 8,
  },
  {
    id: "kun-chiang",
    name: "กุนเชียง",
    emoji: "🌭",
    category: "เนื้อสัตว์",
    grams: 30,
    unit: "ชิ้น",
    kcal: 134,
    protein: 5,
    carbs: 6,
    fat: 10,
  },
  {
    id: "naem",
    name: "แหนม",
    emoji: "🍖",
    category: "เนื้อสัตว์",
    grams: 50,
    unit: "ชิ้น",
    kcal: 94,
    protein: 7,
    carbs: 3,
    fat: 6,
  },
  {
    id: "pork-liver",
    name: "ตับหมู",
    emoji: "🍖",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 132,
    protein: 21,
    carbs: 3,
    fat: 4,
  },
  {
    id: "pork-blood",
    name: "เลือดหมู",
    emoji: "🟥",
    category: "เนื้อสัตว์",
    grams: 100,
    unit: "ถ้วย",
    kcal: 54,
    protein: 12,
    carbs: 0.5,
    fat: 0.5,
  },
  {
    id: "dried-squid",
    name: "ปลาหมึกแห้ง",
    emoji: "🦑",
    category: "เนื้อสัตว์",
    grams: 30,
    unit: "ชิ้น",
    kcal: 89,
    protein: 19,
    carbs: 1,
    fat: 1,
  },
  {
    id: "dried-shrimp",
    name: "กุ้งแห้ง",
    emoji: "🍤",
    category: "เนื้อสัตว์",
    grams: 10,
    unit: "ช้อนโต๊ะ",
    kcal: 24,
    protein: 5,
    carbs: 0.3,
    fat: 0.3,
  },
  {
    id: "pla-ra",
    name: "ปลาร้า",
    emoji: "🐟",
    category: "เนื้อสัตว์",
    grams: 20,
    unit: "ช้อนโต๊ะ",
    kcal: 23,
    protein: 3,
    carbs: 0.5,
    fat: 1,
  },
  {
    id: "chicken-nugget",
    name: "นักเก็ตไก่",
    emoji: "🍗",
    category: "เนื้อสัตว์",
    grams: 25,
    unit: "ชิ้น",
    kcal: 66,
    protein: 3.5,
    carbs: 4,
    fat: 4,
  },
  {
    id: "egg-fried-plain",
    name: "ไข่ดาวน้ำมันน้อย",
    emoji: "🍳",
    category: "นม ไข่",
    grams: 55,
    unit: "ฟอง",
    kcal: 91,
    protein: 6.5,
    carbs: 0.4,
    fat: 7,
  },
  {
    id: "egg-omelette-plain",
    name: "ไข่เจียว",
    emoji: "🍳",
    category: "นม ไข่",
    grams: 70,
    unit: "ฟอง",
    kcal: 149,
    protein: 7,
    carbs: 1,
    fat: 13,
  },
  {
    id: "egg-steamed",
    name: "ไข่ตุ๋น",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 150,
    unit: "ถ้วย",
    kcal: 111,
    protein: 10,
    carbs: 2,
    fat: 7,
  },
  {
    id: "egg-scrambled",
    name: "ไข่คน",
    emoji: "🍳",
    category: "นม ไข่",
    grams: 70,
    unit: "ฟอง",
    kcal: 113,
    protein: 7,
    carbs: 1,
    fat: 9,
  },
  {
    id: "egg-white",
    name: "ไข่ขาว",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 33,
    unit: "ฟอง",
    kcal: 16,
    protein: 3.6,
    carbs: 0.2,
    fat: 0.1,
  },
  {
    id: "egg-yolk",
    name: "ไข่แดง",
    emoji: "🟡",
    category: "นม ไข่",
    grams: 17,
    unit: "ฟอง",
    kcal: 54,
    protein: 2.7,
    carbs: 0.6,
    fat: 4.5,
  },
  {
    id: "duck-egg",
    name: "ไข่เป็ดต้ม",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 70,
    unit: "ฟอง",
    kcal: 126,
    protein: 9,
    carbs: 1,
    fat: 9.6,
  },
  {
    id: "century-egg",
    name: "ไข่เยี่ยวม้า",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 60,
    unit: "ฟอง",
    kcal: 106,
    protein: 7,
    carbs: 1.5,
    fat: 8,
  },
  {
    id: "salted-egg",
    name: "ไข่เค็ม",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 60,
    unit: "ฟอง",
    kcal: 115,
    protein: 7,
    carbs: 1.5,
    fat: 9,
  },
  {
    id: "quail-egg",
    name: "ไข่นกกระทา",
    emoji: "🥚",
    category: "นม ไข่",
    grams: 10,
    unit: "ฟอง",
    kcal: 16,
    protein: 1.3,
    carbs: 0.1,
    fat: 1.1,
  },
  {
    id: "milk-whole",
    name: "นมสดรสจืด",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 128,
    protein: 6.6,
    carbs: 9.6,
    fat: 7,
  },
  {
    id: "milk-lowfat",
    name: "นมพร่องมันเนย",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 93,
    protein: 6.8,
    carbs: 9.8,
    fat: 3,
  },
  {
    id: "milk-skim",
    name: "นมขาดมันเนย",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 71,
    protein: 6.9,
    carbs: 10,
    fat: 0.4,
  },
  {
    id: "milk-choc",
    name: "นมช็อกโกแลต",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 159,
    protein: 6.5,
    carbs: 22,
    fat: 5,
  },
  {
    id: "soymilk",
    name: "นมถั่วเหลืองหวานน้อย",
    emoji: "🫘",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 96,
    protein: 6,
    carbs: 10,
    fat: 3.6,
  },
  {
    id: "almond-milk",
    name: "นมอัลมอนด์ไม่หวาน",
    emoji: "🌰",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 34,
    protein: 1,
    carbs: 1.6,
    fat: 2.6,
  },
  {
    id: "oat-milk",
    name: "นมข้าวโอ๊ต",
    emoji: "🌾",
    category: "นม ไข่",
    grams: 200,
    unit: "กล่อง",
    kcal: 99,
    protein: 2,
    carbs: 16,
    fat: 3,
  },
  {
    id: "yogurt-greek",
    name: "โยเกิร์ตกรีก",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 150,
    unit: "ถ้วย",
    kcal: 120,
    protein: 15,
    carbs: 6,
    fat: 4,
  },
  {
    id: "yogurt-fruit",
    name: "โยเกิร์ตผลไม้",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 150,
    unit: "ถ้วย",
    kcal: 138,
    protein: 5,
    carbs: 24,
    fat: 2.5,
  },
  {
    id: "drinking-yogurt",
    name: "นมเปรี้ยวพร้อมดื่ม",
    emoji: "🥤",
    category: "นม ไข่",
    grams: 180,
    unit: "ขวด",
    kcal: 116,
    protein: 2,
    carbs: 26,
    fat: 0.5,
  },
  {
    id: "cheese-cheddar",
    name: "ชีสเชดดาร์",
    emoji: "🧀",
    category: "นม ไข่",
    grams: 20,
    unit: "แผ่น",
    kcal: 81,
    protein: 5,
    carbs: 0.5,
    fat: 6.6,
  },
  {
    id: "cheese-mozzarella",
    name: "มอสซาเรลลา",
    emoji: "🧀",
    category: "นม ไข่",
    grams: 50,
    unit: "ถ้วย",
    kcal: 149,
    protein: 11,
    carbs: 1.5,
    fat: 11,
  },
  {
    id: "cream-cheese",
    name: "ครีมชีส",
    emoji: "🧀",
    category: "นม ไข่",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 51,
    protein: 1,
    carbs: 0.6,
    fat: 5,
  },
  {
    id: "butter",
    name: "เนย",
    emoji: "🧈",
    category: "นม ไข่",
    grams: 5,
    unit: "ช้อนชา",
    kcal: 37,
    protein: 0.1,
    carbs: 0,
    fat: 4.1,
  },
  {
    id: "whipped-cream",
    name: "วิปครีม",
    emoji: "🍦",
    category: "นม ไข่",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 50,
    protein: 0.3,
    carbs: 1,
    fat: 5,
  },
  {
    id: "condensed-milk",
    name: "นมข้นหวาน",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 20,
    unit: "ช้อนโต๊ะ",
    kcal: 64,
    protein: 1.5,
    carbs: 10.8,
    fat: 1.7,
  },
  {
    id: "evaporated-milk",
    name: "นมข้นจืด",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 21,
    protein: 1,
    carbs: 1.5,
    fat: 1.2,
  },
  {
    id: "milk-powder",
    name: "นมผง",
    emoji: "🥛",
    category: "นม ไข่",
    grams: 12,
    unit: "ช้อนโต๊ะ",
    kcal: 60,
    protein: 3.2,
    carbs: 4.6,
    fat: 3.2,
  },
  {
    id: "whey-protein",
    name: "เวย์โปรตีน",
    emoji: "💪",
    category: "นม ไข่",
    grams: 30,
    unit: "สกู๊ป",
    kcal: 118,
    protein: 24,
    carbs: 2,
    fat: 1.5,
  },
  {
    id: "rice-brown",
    name: "ข้าวกล้อง",
    emoji: "🍚",
    category: "อื่นๆ",
    grams: 80,
    unit: "ทัพพี",
    kcal: 108,
    protein: 2.6,
    carbs: 22.8,
    fat: 0.7,
  },
  {
    id: "rice-sticky",
    name: "ข้าวเหนียวนึ่ง",
    emoji: "🍚",
    category: "อื่นๆ",
    grams: 80,
    unit: "ทัพพี",
    kcal: 121,
    protein: 3.2,
    carbs: 26.6,
    fat: 0.2,
  },
  {
    id: "rice-riceberry",
    name: "ข้าวไรซ์เบอร์รี",
    emoji: "🍚",
    category: "อื่นๆ",
    grams: 80,
    unit: "ทัพพี",
    kcal: 107,
    protein: 2.8,
    carbs: 22,
    fat: 0.9,
  },
  {
    id: "rice-jasmine-2",
    name: "ข้าวสวยหอมมะลิ 2 ทัพพี",
    emoji: "🍚",
    category: "อื่นๆ",
    grams: 160,
    unit: "ชุด",
    kcal: 201,
    protein: 4.4,
    carbs: 45,
    fat: 0.4,
  },
  {
    id: "bread-white",
    name: "ขนมปังขาว",
    emoji: "🍞",
    category: "อื่นๆ",
    grams: 30,
    unit: "แผ่น",
    kcal: 75,
    protein: 2.4,
    carbs: 14,
    fat: 1,
  },
  {
    id: "bread-whole",
    name: "ขนมปังโฮลวีต",
    emoji: "🍞",
    category: "อื่นๆ",
    grams: 32,
    unit: "แผ่น",
    kcal: 77,
    protein: 3.5,
    carbs: 13,
    fat: 1.2,
  },
  {
    id: "bread-toast-butter",
    name: "ขนมปังปิ้งเนย",
    emoji: "🍞",
    category: "อื่นๆ",
    grams: 38,
    unit: "แผ่น",
    kcal: 118,
    protein: 2.5,
    carbs: 14.5,
    fat: 5.5,
  },
  {
    id: "noodle-sen-lek",
    name: "เส้นเล็กลวก",
    emoji: "🍜",
    category: "อื่นๆ",
    grams: 150,
    unit: "ถ้วย",
    kcal: 142,
    protein: 2.5,
    carbs: 32,
    fat: 0.4,
  },
  {
    id: "noodle-bamee",
    name: "เส้นบะหมี่ลวก",
    emoji: "🍜",
    category: "อื่นๆ",
    grams: 80,
    unit: "ก้อน",
    kcal: 158,
    protein: 5,
    carbs: 30,
    fat: 2,
  },
  {
    id: "woonsen",
    name: "วุ้นเส้นลวก",
    emoji: "🍜",
    category: "อื่นๆ",
    grams: 150,
    unit: "ถ้วย",
    kcal: 120,
    protein: 0.1,
    carbs: 30,
    fat: 0,
  },
  {
    id: "macaroni-plain",
    name: "มักกะโรนีลวก",
    emoji: "🍝",
    category: "อื่นๆ",
    grams: 140,
    unit: "ถ้วย",
    kcal: 152,
    protein: 5,
    carbs: 31,
    fat: 0.9,
  },
  {
    id: "spaghetti-plain",
    name: "สปาเกตตีลวก",
    emoji: "🍝",
    category: "อื่นๆ",
    grams: 140,
    unit: "ถ้วย",
    kcal: 158,
    protein: 5.5,
    carbs: 32,
    fat: 0.9,
  },
  {
    id: "mama-plain",
    name: "มาม่าซองมาตรฐาน",
    emoji: "🍜",
    category: "อื่นๆ",
    grams: 60,
    unit: "ซอง",
    kcal: 362,
    protein: 7,
    carbs: 52,
    fat: 14,
  },
  {
    id: "cereal-corn",
    name: "ซีเรียลคอร์นเฟลก",
    emoji: "🥣",
    category: "อื่นๆ",
    grams: 30,
    unit: "ถ้วย",
    kcal: 111,
    protein: 2,
    carbs: 25,
    fat: 0.3,
  },
  {
    id: "roti",
    name: "โรตี",
    emoji: "🫓",
    category: "อื่นๆ",
    grams: 80,
    unit: "แผ่น",
    kcal: 274,
    protein: 5,
    carbs: 32,
    fat: 14,
  },
  {
    id: "tortilla",
    name: "แป้งตอร์ตียา",
    emoji: "🫓",
    category: "อื่นๆ",
    grams: 45,
    unit: "แผ่น",
    kcal: 129,
    protein: 3.5,
    carbs: 22,
    fat: 3,
  },
  {
    id: "patongko",
    name: "ปาท่องโก๋",
    emoji: "🥖",
    category: "อื่นๆ",
    grams: 40,
    unit: "คู่",
    kcal: 156,
    protein: 3,
    carbs: 18,
    fat: 8,
  },
  {
    id: "khanom-krok",
    name: "ขนมครก",
    emoji: "🥥",
    category: "อื่นๆ",
    grams: 40,
    unit: "คู่",
    kcal: 80,
    protein: 1,
    carbs: 10,
    fat: 4,
  },
  {
    id: "khanom-tuay",
    name: "ขนมถ้วย",
    emoji: "🍮",
    category: "อื่นๆ",
    grams: 40,
    unit: "ถ้วย",
    kcal: 74,
    protein: 0.8,
    carbs: 11,
    fat: 3,
  },
  {
    id: "thong-yip",
    name: "ทองหยิบ",
    emoji: "🟡",
    category: "อื่นๆ",
    grams: 20,
    unit: "ชิ้น",
    kcal: 68,
    protein: 1.5,
    carbs: 12,
    fat: 1.5,
  },
  {
    id: "foy-thong",
    name: "ฝอยทอง",
    emoji: "🟡",
    category: "อื่นๆ",
    grams: 20,
    unit: "ชิ้น",
    kcal: 66,
    protein: 1.8,
    carbs: 12,
    fat: 1.2,
  },
  {
    id: "khanom-chan",
    name: "ขนมชั้น",
    emoji: "🟩",
    category: "อื่นๆ",
    grams: 30,
    unit: "ชิ้น",
    kcal: 80,
    protein: 0.4,
    carbs: 15,
    fat: 2,
  },
  {
    id: "khao-niew-mamuang",
    name: "ข้าวเหนียวมะม่วง",
    emoji: "🥭",
    category: "อื่นๆ",
    grams: 220,
    unit: "จาน",
    kcal: 400,
    protein: 5,
    carbs: 68,
    fat: 12,
  },
  {
    id: "kluay-tod",
    name: "กล้วยทอด",
    emoji: "🍌",
    category: "อื่นๆ",
    grams: 40,
    unit: "ชิ้น",
    kcal: 127,
    protein: 1,
    carbs: 15,
    fat: 7,
  },
  {
    id: "kluay-buat-chi",
    name: "กล้วยบวชชี",
    emoji: "🥥",
    category: "อื่นๆ",
    grams: 180,
    unit: "ถ้วย",
    kcal: 226,
    protein: 2,
    carbs: 32,
    fat: 10,
  },
  {
    id: "bua-loy",
    name: "บัวลอยน้ำขิง",
    emoji: "⚪",
    category: "อื่นๆ",
    grams: 180,
    unit: "ถ้วย",
    kcal: 234,
    protein: 3,
    carbs: 42,
    fat: 6,
  },
  {
    id: "tabtim-krob",
    name: "ทับทิมกรอบ",
    emoji: "🔴",
    category: "อื่นๆ",
    grams: 180,
    unit: "ถ้วย",
    kcal: 247,
    protein: 1.5,
    carbs: 40,
    fat: 9,
  },
  {
    id: "lod-chong",
    name: "ลอดช่องน้ำกะทิ",
    emoji: "🟢",
    category: "อื่นๆ",
    grams: 180,
    unit: "ถ้วย",
    kcal: 248,
    protein: 1.5,
    carbs: 38,
    fat: 10,
  },
  {
    id: "french-fries",
    name: "มันฝรั่งทอด",
    emoji: "🍟",
    category: "อื่นๆ",
    grams: 100,
    unit: "ถ้วย",
    kcal: 313,
    protein: 3.4,
    carbs: 41,
    fat: 15,
  },
  {
    id: "potato-chips",
    name: "มันฝรั่งแผ่นทอด",
    emoji: "🥔",
    category: "อื่นๆ",
    grams: 30,
    unit: "ซองเล็ก",
    kcal: 157,
    protein: 1.8,
    carbs: 15,
    fat: 10,
  },
  {
    id: "popcorn-plain",
    name: "ป๊อปคอร์นไม่ใส่เนย",
    emoji: "🍿",
    category: "อื่นๆ",
    grams: 25,
    unit: "ถ้วย",
    kcal: 101,
    protein: 3,
    carbs: 19,
    fat: 1.4,
  },
  {
    id: "peanut",
    name: "ถั่วลิสงคั่ว",
    emoji: "🥜",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 91,
    protein: 3.9,
    carbs: 2.4,
    fat: 7.3,
  },
  {
    id: "cashew",
    name: "เม็ดมะม่วงหิมพานต์",
    emoji: "🌰",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 88,
    protein: 2.7,
    carbs: 4.4,
    fat: 6.6,
  },
  {
    id: "almond",
    name: "อัลมอนด์",
    emoji: "🌰",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 94,
    protein: 3.2,
    carbs: 3.3,
    fat: 7.5,
  },
  {
    id: "walnut",
    name: "วอลนัท",
    emoji: "🌰",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 105,
    protein: 2.3,
    carbs: 2,
    fat: 9.8,
  },
  {
    id: "sunflower-seed",
    name: "เมล็ดทานตะวัน",
    emoji: "🌻",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 94,
    protein: 3.1,
    carbs: 3,
    fat: 7.7,
  },
  {
    id: "chia",
    name: "เมล็ดเจีย",
    emoji: "⚫",
    category: "อื่นๆ",
    grams: 12,
    unit: "ช้อนโต๊ะ",
    kcal: 61,
    protein: 2,
    carbs: 5,
    fat: 3.7,
  },
  {
    id: "biscuit",
    name: "บิสกิต",
    emoji: "🍪",
    category: "อื่นๆ",
    grams: 12,
    unit: "ชิ้น",
    kcal: 53,
    protein: 0.7,
    carbs: 8,
    fat: 2,
  },
  {
    id: "cookie-choc",
    name: "คุกกี้ช็อกชิป",
    emoji: "🍪",
    category: "อื่นๆ",
    grams: 20,
    unit: "ชิ้น",
    kcal: 97,
    protein: 1.2,
    carbs: 13,
    fat: 4.5,
  },
  {
    id: "cake-butter",
    name: "เค้กเนยสด",
    emoji: "🍰",
    category: "อื่นๆ",
    grams: 80,
    unit: "ชิ้น",
    kcal: 294,
    protein: 4,
    carbs: 38,
    fat: 14,
  },
  {
    id: "brownie",
    name: "บราวนี่",
    emoji: "🍫",
    category: "อื่นๆ",
    grams: 60,
    unit: "ชิ้น",
    kcal: 250,
    protein: 3.5,
    carbs: 32,
    fat: 12,
  },
  {
    id: "donut",
    name: "โดนัทเคลือบน้ำตาล",
    emoji: "🍩",
    category: "อื่นๆ",
    grams: 60,
    unit: "ชิ้น",
    kcal: 242,
    protein: 3.5,
    carbs: 30,
    fat: 12,
  },
  {
    id: "croissant",
    name: "ครัวซองต์",
    emoji: "🥐",
    category: "อื่นๆ",
    grams: 60,
    unit: "ชิ้น",
    kcal: 232,
    protein: 5,
    carbs: 26,
    fat: 12,
  },
  {
    id: "ice-cream",
    name: "ไอศกรีมวานิลลา",
    emoji: "🍦",
    category: "อื่นๆ",
    grams: 60,
    unit: "สกู๊ป",
    kcal: 128,
    protein: 2.2,
    carbs: 14,
    fat: 7,
  },
  {
    id: "chocolate-milk-bar",
    name: "ช็อกโกแลตนม",
    emoji: "🍫",
    category: "อื่นๆ",
    grams: 30,
    unit: "แท่ง",
    kcal: 159,
    protein: 2.5,
    carbs: 17,
    fat: 9,
  },
  {
    id: "jelly",
    name: "เยลลี่",
    emoji: "🍬",
    category: "อื่นๆ",
    grams: 80,
    unit: "ถ้วย",
    kcal: 76,
    protein: 1,
    carbs: 18,
    fat: 0,
  },
  {
    id: "marshmallow",
    name: "มาร์ชเมลโลว์",
    emoji: "🍬",
    category: "อื่นๆ",
    grams: 7,
    unit: "ชิ้น",
    kcal: 24,
    protein: 0.1,
    carbs: 5.8,
    fat: 0,
  },
  {
    id: "water",
    name: "น้ำเปล่า",
    emoji: "💧",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
  },
  {
    id: "green-tea-plain",
    name: "ชาเขียวไม่หวาน",
    emoji: "🍵",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 1,
    protein: 0,
    carbs: 0.3,
    fat: 0,
  },
  {
    id: "coffee-black",
    name: "กาแฟดำไม่ใส่น้ำตาล",
    emoji: "☕",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 1,
    protein: 0.3,
    carbs: 0,
    fat: 0,
  },
  {
    id: "coffee-latte",
    name: "ลาเต้ร้อน",
    emoji: "☕",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 135,
    protein: 7,
    carbs: 11,
    fat: 7,
  },
  {
    id: "coffee-ice-sweet",
    name: "กาแฟเย็น",
    emoji: "🧋",
    category: "อื่นๆ",
    grams: 350,
    unit: "แก้ว",
    kcal: 229,
    protein: 3,
    carbs: 34,
    fat: 9,
  },
  {
    id: "thai-tea",
    name: "ชาไทยเย็น",
    emoji: "🧋",
    category: "อื่นๆ",
    grams: 350,
    unit: "แก้ว",
    kcal: 270,
    protein: 3,
    carbs: 42,
    fat: 10,
  },
  {
    id: "milk-tea",
    name: "ชานมไข่มุก",
    emoji: "🧋",
    category: "อื่นๆ",
    grams: 400,
    unit: "แก้ว",
    kcal: 354,
    protein: 4,
    carbs: 62,
    fat: 10,
  },
  {
    id: "soda-cola",
    name: "น้ำอัดลม",
    emoji: "🥤",
    category: "อื่นๆ",
    grams: 325,
    unit: "กระป๋อง",
    kcal: 140,
    protein: 0,
    carbs: 35,
    fat: 0,
  },
  {
    id: "orange-juice",
    name: "น้ำส้มคั้น",
    emoji: "🍊",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 115,
    protein: 1.7,
    carbs: 26,
    fat: 0.5,
  },
  {
    id: "coconut-water",
    name: "น้ำมะพร้าว",
    emoji: "🥥",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 47,
    protein: 1.7,
    carbs: 9,
    fat: 0.5,
  },
  {
    id: "smoothie-fruit",
    name: "สมูทตี้ผลไม้",
    emoji: "🥤",
    category: "อื่นๆ",
    grams: 300,
    unit: "แก้ว",
    kcal: 185,
    protein: 2,
    carbs: 42,
    fat: 1,
  },
  {
    id: "soy-drink-sweet",
    name: "น้ำเต้าหู้",
    emoji: "🥛",
    category: "อื่นๆ",
    grams: 250,
    unit: "แก้ว",
    kcal: 152,
    protein: 7,
    carbs: 22,
    fat: 4,
  },
  {
    id: "beer",
    name: "เบียร์",
    emoji: "🍺",
    category: "อื่นๆ",
    grams: 330,
    unit: "กระป๋อง",
    kcal: 49,
    protein: 1.6,
    carbs: 10.6,
    fat: 0,
  },
  {
    id: "oil-vegetable",
    name: "น้ำมันพืช",
    emoji: "🫗",
    category: "อื่นๆ",
    grams: 14,
    unit: "ช้อนโต๊ะ",
    kcal: 126,
    protein: 0,
    carbs: 0,
    fat: 14,
  },
  {
    id: "coconut-milk",
    name: "กะทิ",
    emoji: "🥥",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 36,
    protein: 0.3,
    carbs: 0.8,
    fat: 3.5,
  },
  {
    id: "mayonnaise",
    name: "มายองเนส",
    emoji: "🥄",
    category: "อื่นๆ",
    grams: 14,
    unit: "ช้อนโต๊ะ",
    kcal: 93,
    protein: 0.2,
    carbs: 0.6,
    fat: 10,
  },
  {
    id: "ketchup",
    name: "ซอสมะเขือเทศ",
    emoji: "🍅",
    category: "อื่นๆ",
    grams: 17,
    unit: "ช้อนโต๊ะ",
    kcal: 19,
    protein: 0.2,
    carbs: 4.5,
    fat: 0,
  },
  {
    id: "fish-sauce",
    name: "น้ำปลา",
    emoji: "🫗",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 8,
    protein: 1.4,
    carbs: 0.6,
    fat: 0,
  },
  {
    id: "soy-sauce",
    name: "ซีอิ๊วขาว",
    emoji: "🫗",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 8,
    protein: 1.3,
    carbs: 0.8,
    fat: 0,
  },
  {
    id: "oyster-sauce",
    name: "ซอสหอยนางรม",
    emoji: "🦪",
    category: "อื่นๆ",
    grams: 18,
    unit: "ช้อนโต๊ะ",
    kcal: 39,
    protein: 0.8,
    carbs: 9,
    fat: 0,
  },
  {
    id: "sugar",
    name: "น้ำตาลทราย",
    emoji: "🍬",
    category: "อื่นๆ",
    grams: 4,
    unit: "ช้อนชา",
    kcal: 16,
    protein: 0,
    carbs: 4,
    fat: 0,
  },
  {
    id: "honey",
    name: "น้ำผึ้ง",
    emoji: "🍯",
    category: "อื่นๆ",
    grams: 7,
    unit: "ช้อนชา",
    kcal: 23,
    protein: 0,
    carbs: 5.8,
    fat: 0,
  },
  {
    id: "nam-prik-pao",
    name: "น้ำพริกเผา",
    emoji: "🌶️",
    category: "อื่นๆ",
    grams: 15,
    unit: "ช้อนโต๊ะ",
    kcal: 45,
    protein: 0.6,
    carbs: 4,
    fat: 3,
  },
  {
    id: "tofu-firm",
    name: "เต้าหู้แข็ง",
    emoji: "🧊",
    category: "อื่นๆ",
    grams: 100,
    unit: "ชิ้น",
    kcal: 121,
    protein: 12,
    carbs: 2.5,
    fat: 7,
  },
  {
    id: "tofu-soft",
    name: "เต้าหู้อ่อน",
    emoji: "🧊",
    category: "อื่นๆ",
    grams: 100,
    unit: "หลอด",
    kcal: 55,
    protein: 5,
    carbs: 2,
    fat: 3,
  },
  {
    id: "tempeh",
    name: "เทมเป้",
    emoji: "🫘",
    category: "อื่นๆ",
    grams: 80,
    unit: "ชิ้น",
    kcal: 151,
    protein: 15,
    carbs: 7,
    fat: 7,
  },
  {
    id: "edamame",
    name: "ถั่วแระญี่ปุ่น",
    emoji: "🫛",
    category: "อื่นๆ",
    grams: 100,
    unit: "ถ้วย",
    kcal: 129,
    protein: 11,
    carbs: 10,
    fat: 5,
  },
  {
    id: "red-bean",
    name: "ถั่วแดงต้ม",
    emoji: "🫘",
    category: "อื่นๆ",
    grams: 100,
    unit: "ถ้วย",
    kcal: 124,
    protein: 8,
    carbs: 22,
    fat: 0.5,
  },
  {
    id: "black-bean",
    name: "ถั่วดำต้ม",
    emoji: "🫘",
    category: "อื่นๆ",
    grams: 100,
    unit: "ถ้วย",
    kcal: 136,
    protein: 8.9,
    carbs: 24,
    fat: 0.5,
  },
  {
    id: "kidney-bean",
    name: "ถั่วขาวต้ม",
    emoji: "🫘",
    category: "อื่นๆ",
    grams: 100,
    unit: "ถ้วย",
    kcal: 127,
    protein: 8.7,
    carbs: 22,
    fat: 0.5,
  },
  {
    id: "seaweed-snack",
    name: "สาหร่ายอบกรอบ",
    emoji: "🟩",
    category: "อื่นๆ",
    grams: 5,
    unit: "ซอง",
    kcal: 26,
    protein: 1.5,
    carbs: 1.5,
    fat: 1.5,
  },
  {
    id: "konjac",
    name: "บุก",
    emoji: "⚪",
    category: "อื่นๆ",
    grams: 150,
    unit: "ถ้วย",
    kcal: 17,
    protein: 0.3,
    carbs: 4,
    fat: 0,
  },
];
