import { StyleSheet } from "react-native";
export const C = {
  bg: "#F7F8F2",
  white: "#FFFFFF",
  green: "#245C43",
  dark: "#183D2E",
  muted: "#69766B",
  border: "#E5E9DF",
  lime: "#DDEDAB",
  soft: "#EDF3E5",
  peach: "#FCEAE2",
  purple: "#EFEBFB",
  blue: "#E9F4FA",
};
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  app: { flex: 1, flexDirection: "row" },
  center: {
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    padding: 24,
  },
  text: { fontFamily: "NotoSansThai_400Regular", fontSize: 14, color: C.dark },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  title: {
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 30,
    lineHeight: 46,
    color: C.dark,
  },
  subtitle: { fontSize: 13, color: C.muted, lineHeight: 23 },
  caption: { fontSize: 12, color: C.muted, lineHeight: 20 },
  label: { fontFamily: "NotoSansThai_500Medium", fontSize: 14 },
  cardTitle: { fontFamily: "NotoSansThai_600SemiBold", fontSize: 16 },
  eyebrow: {
    fontFamily: "NotoSansThai_600SemiBold",
    fontSize: 10,
    letterSpacing: 1.5,
    color: C.muted,
    marginBottom: 7,
  },
  bigNumber: {
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 40,
    lineHeight: 55,
    color: C.dark,
  },
  card: {
    backgroundColor: C.white,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.border,
    padding: 22,
  },
  content: { padding: 20, paddingBottom: 20 },
  page: { width: "100%", maxWidth: 1150, alignSelf: "center" },
  columns: { flexDirection: "row", gap: 20, alignItems: "stretch" },
  sidebar: {
    width: 254,
    backgroundColor: "#FCFDF9",
    borderRightWidth: 1,
    borderColor: C.border,
    padding: 24,
    paddingTop: 35,
  },
  brand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 52,
  },
  brandIcon: {
    backgroundColor: C.green,
    width: 42,
    height: 45,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  brandName: {
    fontFamily: "NotoSansThai_700Bold",
    fontSize: 23,
    letterSpacing: -0.8,
  },
  sideNav: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 16,
    borderRadius: 12,
    marginTop: 8,
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.lime,
    marginLeft: "auto",
  },
  sideNote: { backgroundColor: C.soft, borderRadius: 18, padding: 20, gap: 10 },
  avatar: {
    height: 48,
    width: 48,
    borderRadius: 24,
    backgroundColor: "#E9EEDC",
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    backgroundColor: C.green,
    borderRadius: 12,
    minHeight: 49,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
  },
  secondary: { backgroundColor: C.soft },
  buttonText: {
    fontFamily: "NotoSansThai_600SemiBold",
    fontSize: 14,
    color: "white",
  },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  datePicker: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    gap: 6,
  },
  badge: {
    backgroundColor: C.soft,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
  },
  badgeText: {
    fontFamily: "NotoSansThai_500Medium",
    fontSize: 11,
    color: C.green,
  },
  ring: { width: 188, height: 188 },
  ringLabel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  macro: { padding: 12, borderRadius: 11, gap: 9 },
  track: {
    height: 5,
    borderRadius: 5,
    backgroundColor: "#FFFFFF99",
    overflow: "hidden",
  },
  fill: { height: "100%", borderRadius: 5 },
  mealSection: {
    borderTopWidth: 1,
    borderColor: C.border,
    paddingTop: 8,
    marginTop: 12,
    paddingBottom: 4,
  },
  smallFood: {
    width: 47,
    height: 47,
    backgroundColor: C.bg,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  lightIcon: {
    width: 44,
    height: 44,
    backgroundColor: "#FFFFFF12",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
  },
  gentleNote: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    padding: 20,
    backgroundColor: C.soft,
    borderRadius: 16,
  },
  footer: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 30,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: C.white,
    borderTopWidth: 1,
    borderColor: C.border,
    paddingTop: 8,
    paddingBottom: 8,
  },
  bottomItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minHeight: 56,
  },
  navIcon: { paddingVertical: 5, paddingHorizontal: 20, borderRadius: 15 },
  input: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: "#BEC8B9",
    borderRadius: 11,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: "NotoSansThai_400Regular",
    fontSize: 16,
    color: C.dark,
    backgroundColor: "#FCFDF9",
  },
  search: {
    backgroundColor: C.bg,
    borderRadius: 12,
    paddingHorizontal: 13,
    marginTop: 8,
  },
  chip: {
    minHeight: 43,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    justifyContent: "center",
  },
  chipText: { fontSize: 12, fontFamily: "NotoSansThai_500Medium" },
  foodGrid: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  foodCard: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 18,
    padding: 17,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  foodEmoji: {
    height: 77,
    width: 77,
    borderRadius: 20,
    backgroundColor: "#F0F1E7",
    alignItems: "center",
    justifyContent: "center",
  },
  empty: { paddingVertical: 34, alignItems: "center", gap: 10 },
  emptyIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: C.soft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  historyRow: {
    borderTopWidth: 1,
    borderColor: C.border,
    marginTop: 12,
    paddingTop: 10,
  },
  toast: {
    position: "absolute",
    bottom: 100,
    alignSelf: "center",
    maxWidth: "92%",
    backgroundColor: C.dark,
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 14,
    flexDirection: "row",
    gap: 9,
    alignItems: "center",
  },
  overlay: {
    flex: 1,
    backgroundColor: "#132D2477",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modal: {
    width: "100%",
    maxWidth: 470,
    maxHeight: "92%",
    backgroundColor: C.white,
    borderRadius: 24,
    overflow: "hidden",
  },
  summary: { backgroundColor: C.soft, borderRadius: 15, padding: 18 },
  error: { color: "#A34337", fontSize: 13, lineHeight: 23 },
  notice: {
    padding: 16,
    backgroundColor: "#FFF0E8",
    borderRadius: 12,
    marginTop: 16,
    gap: 10,
  },
});
